### PR TITLE
Update spring boot, liquibase, jgit

### PR DESCRIPTION
**Pull request by kinow**
## Description

Updating dependencies, and building the project now with Java 17 (LTS). Had to replace Cobertura by JaCoCo in order to get the build green. The test coverage reduced, but that's because Cobertura was reporting incorrectly (see comment below about it).

## Motivation and Context

Proactively updating a few dependencies.

## How Has This Been Tested?

- [x] `mvn clean test`
- [x] Running Docker Compose locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mr-c** [comment]
https://github.com/common-workflow-language/cwlviewer/runs/6405459959?check_suite_focus=true#step:6:384

Time to upgrade to something newer than Java 8?

**Comment by kinow** [comment]
> https://github.com/common-workflow-language/cwlviewer/runs/6405459959?check_suite_focus=true#step:6:384
> 
> Time to upgrade to something newer than Java 8?

Good idea. Probably latest LTS 17 if it works with our dependencies & deployment - https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by kinow** [comment]
Upgraded to Java 17, then had to update the build tooling too. Upgraded the maven plug-ins, it broke coverage. Fixed coverage, now the report is complaining it was reduced in 7.1 % :sweat_smile: Almost there! More tomorrow.

**Comment by kinow** [comment]
image

image

There are way more files in the JaCoCo report than in the Cobertura one. And Cobertura appears to have been broken for a while. I confirmed `GitDetails.java` that was 100% for Cobertura is not actually fully covered by our tests. So the JaCoCo number looks correct :+1:

**Review by mr-c — APPROVED** [review]

**Comment by kinow** [comment]
@mr-c updated the branch, but I cannot merge it, could you merge it if it's looking OK to you, please? Thanks!!! :pray: 

image

**Comment by kinow** [comment]
Coverage will go down due to a problem at how Cobertura was counting covered code. But we will increase that later :muscle:

**Pull request merged**
