### PR TITLE
Separate workflow URL from repository URL in "retrieved from" column of workflows page

### PR DESCRIPTION
**Pull request by obasekiosa**
## Description

Previously the repository link in the "retrieved from" column of the workflows.html page referenced the workflow file while its text displayed the workflow repository. This change ensures both the workflow repo and the file are displayed separately. 

## Motivation and Context

This change prevents ambiguity for users when using the workflows page.
It shows two separate links each for the repository and workflow file.

For Issue #313: Link in the "retrieved from" column is confusing (#313)

## Layout before the change:
image

## Layout after the change:
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by obasekiosa** [comment]
> Thanks! Would it perhaps make more sense to make the `blob/master` long URL be the hyperlink of the existing `Path: workflows/Chip/peak.cwl` string rather then adding a new line above?

Thanks for the feedback and suggestion. 
Yes, it would.

So I looked at to code once more to confirm there is no case where for some reason the path is empty but the workflow URL exists and then by consequence the workflow URL is lost, but it seems the workflow URL is built using the path so that would never happen. 

I would be pushing the changes now.

**Comment by obasekiosa** [comment]
**Based on the previous comments the new layout change is as below:**

## Original Layout Before Pull Request
image


## Layout After
image

**Comment by tetron** [comment]
It reports 'out-of-date with the base branch" could you please merge with main or rebase on main?

**Comment by obasekiosa** [comment]
> It reports 'out-of-date with the base branch" could you please merge with main or rebase on main?

I have done this.

**Comment by mr-c** [comment]
Thank you!

**Pull request merged**
