### PR TITLE
Small fixes for issues found during dev/prod deployment

### PR DESCRIPTION
**Pull request by kinow**
A pull request for issues found during the deployment of 1.4.2 to the existing environment.

## Description

Placeholder for all issues found.

## Motivation and Context

Deployment issues.

## How Has This Been Tested?

Unfortunately, while deploying the code :sweat_smile: 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kinow** [comment]
Thanks to Ward for the patience going through the new deployment instructions, and for spotting the `pg_hba.conf` typo.

**Comment by mr-c** [comment]
👍👍👍

**Comment by kinow** [comment]
In the issue https://github.com/common-workflow-language/cwlviewer/issues/395 & PR https://github.com/common-workflow-language/cwlviewer/pull/396, one workflow would not render after migrating the data from MongoDB to PostgreSQL.

After troubleshooting it, I realized it was due to a change in recent versions of Thymeleaf (template used in SpringBoot). It disallows static methods accessed in the template. I've rebased this branch, and added a change to send the result of the static method from the controller, already processed, to the template.

Tested on the workflow that was not rendering and it fixed the problem :tada: :partying_face:

**Comment by mr-c** [comment]
👍 Feel free to self merge

**Pull request merged**
